# Site settings
email:
baseurl: "https://viverefelici.life"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-114817658-1"

# SEO settings
title: VivereFelici
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: "Enica Soldo"
profile_img:/assets/images/.jpg
profile:
social:
  github:

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "vendor"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
